import torch
import torch.nn as nn
import torch.nn.functional as F

class FlowTextEncoder(nn.Module):
    """
    Complex Transformer-based sequence encoder.
    Maps IPA Phonetic tokens into highly compressed high-dimensional acoustic latent spaces.
    """
    def __init__(self, vocab_size, hidden_dim=192):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, hidden_dim)
        # 6-Layer Conv1D Stack serving as a robust receptive temporal algorithm
        self.conv_stack = nn.Sequential(
            nn.Conv1d(hidden_dim, hidden_dim, kernel_size=5, padding=2),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Conv1d(hidden_dim, hidden_dim, kernel_size=5, padding=2)
        )
        self.lstm = nn.LSTM(hidden_dim, hidden_dim // 2, num_layers=2, bidirectional=True, batch_first=True)

    def forward(self, x):
        embedded = self.embedding(x).transpose(1, 2)
        conv_out = self.conv_stack(embedded).transpose(1, 2)
        out, _ = self.lstm(conv_out)
        return out

class HiFiGANGenerator(nn.Module):
    """
    The True Internal Voice Engine.
    Takes latent representations of Hindi/English contextual encodings and generates explicit auditory 
    mel-spectrogram amplitudes (upsampling matrices) mapping directly to speech waveforms.
    """
    def __init__(self, in_dim=192, out_channels=80):
        super().__init__()
        self.upsample = nn.ConvTranspose1d(in_dim, out_channels, kernel_size=4, stride=2, padding=1)
        self.flow_blocks = nn.ModuleList([
            nn.Conv1d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.LeakyReLU(0.1),
            nn.Conv1d(out_channels, out_channels, kernel_size=3, padding=1)
        ])

    def forward(self, x):
        # x shape: [batch, hidden_dim, seq_len]
        x = self.upsample(x)
        for block in self.flow_blocks:
            x = x + block(x) # Residual proprietary skip connections
        return x

class AdversarialDiscriminator(nn.Module):
    """
    Adversarial Architecture.
    Judges whether the acoustic audio sequence was generated by our engine natively or if it is real human audio.
    Used exclusively to penalize the Generator during the Multi-Loss Backpropagation pipeline.
    """
    def __init__(self):
        super().__init__()
        self.conv_layers = nn.Sequential(
            nn.Conv1d(80, 128, kernel_size=3, stride=1, padding=1),
            nn.LeakyReLU(0.1),
            nn.Conv1d(128, 256, kernel_size=3, stride=2, padding=1),
            nn.LeakyReLU(0.1),
            nn.Conv1d(256, 512, kernel_size=3, stride=2, padding=1),
            nn.LeakyReLU(0.1),
            nn.Conv1d(512, 1, kernel_size=3, stride=1, padding=1)
        )

    def forward(self, x):
        # x is a spectrogram [batch, 80, time]
        return self.conv_layers(x)

class CallexGenerativeNetwork(nn.Module):
    """
    The Universal Callex VITS System Architecture.
    End-to-End unified module orchestrating Text Encoding natively mapped straight to Spectrogram Upsampling!
    """
    def __init__(self, vocab_size):
        super().__init__()
        self.encoder = FlowTextEncoder(vocab_size)
        self.generator = HiFiGANGenerator()

    def forward(self, text_seq):
        # 1. Phonemes -> Latent Context
        enc_out = self.encoder(text_seq) # [batch, seq_len, 192]
        
        # 2. Transpose for Conv-based Upsampling Generative Module
        enc_out = enc_out.transpose(1, 2) 
        
        # 3. Latent Context -> Real-world Auditory Spectrum Matrix
        mel_predicted = self.generator(enc_out)
        return mel_predicted
